### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by hail100** [hyperliquid-dex/node#1]
I cannot run hl-visor
```
thread 'main' panicked at /home/ubuntu/cham/code/base/src/c.rs:382:5:
assertion failed: home_dir != "/root"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

**Comment by reiserFSs** [comment]
> I cannot run hl-visor
> 
> ```
> thread 'main' panicked at /home/ubuntu/cham/code/base/src/c.rs:382:5:
> assertion failed: home_dir != "/root"
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Aborted
> ```
Same here
